name: Build Android

on:
  [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "aarch64", "aarch32" ]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev
          pip3 install mako meson ninja

          echo 'export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"' >> $GITHUB_ENV

      - name: Finalize Build Crossfiles
        run: |
          cd pojav

          envsubst <drm-android-${{matrix.arch}}  > drm-build-crossfile
          envsubst <mesa-android-${{matrix.arch}} > mesa-build-crossfile        

      - name: Build DRM
        run: |
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/drm.git
          cd drm

          meson setup "build-android" \
            --prefix=/tmp/drm-static \
            --cross-file "../pojav/drm-build-crossfile" \
            -Dintel=disabled \
            -Dradeon=disabled \
            -Damdgpu=disabled \
            -Dnouveau=disabled \
            -Dvmwgfx=disabled \
            -Dfreedreno=disabled \
            -Dvc4=disabled \
            -Detnaviv=disabled

          ninja -C "build-android" install

      - name: Build Panfrost
        run: |
          meson setup "build-android" \
            --prefix=/tmp/pan \
            -Dtools=panfrost \
            --cross-file "pojav/mesa-build-crossfile" \
            -Dplatforms=android \
            -Dplatform-sdk-version=26 \
            -Dllvm=disabled \
            -Dandroid-stub=true \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dgbm=disabled \
            -Dglx=disabled \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=swrast,panfrost \
            -Dshared-glapi=false \
            -Dc_args="-Wno-error=incompatible-function-pointer-types" \
            -Dbuildtype=release \
            -Dandroid-libbacktrace=disabled

          ninja -C "build-android" install

      - name: Upload Panfrost
        uses: actions/upload-artifact@v4
        with:
          name: panfrost_${{matrix.arch}}
          path: /tmp/pan
