name: Build Android

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm32", "aarch64" ]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:
        
      - uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt update
          sudo apt install -y meson libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev glslang-tools
          pip3 install mako
          
          # Setup Android NDK
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r27c
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          
          # Clone Mesa repository
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/mesa.git
          cd mesa
          
          # Fix blake3 implementation with sed
          # Add declarations to blake3_impl.h
          sed -i '1i\#include <stdint.h>' src/util/blake3/blake3_impl.h
          sed -i '/^#if BLAKE3_USE_NEON == 1/a void blake3_hash_many_neon(const uint8_t *const *inputs, size_t num_inputs, size_t blocks, const uint32_t key[8], uint64_t counter, bool increment_counter, uint8_t flags, uint8_t flags_start, uint8_t flags_end, uint8_t *out);' src/util/blake3/blake3_impl.h
          
          if [ "${{matrix.arch}}" = "aarch64" ]; then
            # For aarch64, replace the entire NEON section with a static implementation
            sed -i '/^#if BLAKE3_USE_NEON == 1/,/^#endif/c\#if BLAKE3_USE_NEON == 1\nstatic void blake3_hash_many_neon(const uint8_t *const *inputs, size_t num_inputs, size_t blocks, const uint32_t key[8], uint64_t counter, bool increment_counter, uint8_t flags, uint8_t flags_start, uint8_t flags_end, uint8_t *out) {\n  blake3_hash_many_portable(inputs, num_inputs, blocks, key, counter, increment_counter, flags, flags_start, flags_end, out);\n}\n#endif' src/util/blake3/blake3_dispatch.c
          else
            # For arm32, use the original fix
            sed -i '/^#if BLAKE3_USE_NEON == 1/,/^#endif/c\#if BLAKE3_USE_NEON == 1\nvoid blake3_hash_many_neon(const uint8_t *const *inputs, size_t num_inputs, size_t blocks, const uint32_t key[8], uint64_t counter, bool increment_counter, uint8_t flags, uint8_t flags_start, uint8_t flags_end, uint8_t *out) {\n  blake3_hash_many_portable(inputs, num_inputs, blocks, key, counter, increment_counter, flags, flags_start, flags_end, out);\n}\n#endif' src/util/blake3/blake3_dispatch.c
          fi
          
          # Add missing include to panvk_android.c
          sed -i '/#include <stdlib.h>/a #include <string.h>' src/panfrost/vulkan/panvk_android.c
          
          # Rest of the build process
          envsubst <$GITHUB_WORKSPACE/android-drm-${{matrix.arch}} >build-crossfile-drm
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/drm.git
          cd drm
          meson setup "build-android" \
            --prefix=/tmp/drm-static \
            --cross-file "../build-crossfile-drm" \
            -Ddefault_library=static \
            -Dintel=disabled \
            -Dradeon=disabled \
            -Damdgpu=disabled \
            -Dnouveau=disabled \
            -Dvmwgfx=disabled \
            -Dfreedreno=disabled \
            -Dvc4=disabled \
            -Detnaviv=disabled
          ninja -C "build-android" install
          cd ..
          envsubst <$GITHUB_WORKSPACE/android-${{matrix.arch}} >build-crossfile
          meson setup "build-android" \
            --prefix=/tmp/pan \
            --cross-file "build-crossfile" \
            -Dplatforms=android \
            -Dplatform-sdk-version=34 \
            -Dandroid-stub=true \
            -Dllvm=disabled \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dgbm=disabled \
            -Dglx=disabled \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers=panfrost,virtio \
            -Dgallium-drivers=softpipe,virgl,panfrost \
            -Dshared-glapi=disabled
          ninja -C "build-android" install
      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: panfrost_${{matrix.arch}}
          path: /tmp/pan
