name: Build "panvk"

on:
  workflow_dispatch:
  schedule:
  - cron: "20 5 1,15 * *"

jobs:
  start_building_panvk:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y
        sudo apt install -y libdrm-dev
    
    - name: Execute build script
      run: |
        mkdir -p panvk_workdir
        cp -r patches panvk_workdir/
        bash ./panvk_builder.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Upload meson and ninja logs for debugging
        path: |
          panvk_workdir/ninja_log
          panvk_workdir/mesa/build-android-aarch64/meson-logs/meson-log.txt
    
    - id: versions
      name: "Get release info"
      run: |
        echo "name=$(cat panvk_workdir/release)" >> "$GITHUB_OUTPUT"
        echo "tag=$(cat panvk_workdir/tag)" >> "$GITHUB_OUTPUT"
        echo "filename=$(cat panvk_workdir/filename)" >> "$GITHUB_OUTPUT"
        echo "patched=$(cat panvk_workdir/patched)" >> "$GITHUB_OUTPUT"
        echo "experimental=$(cat panvk_workdir/experimental)" >> "$GITHUB_OUTPUT"

    - name: Release "panvk"
      uses: softprops/action-gh-release@v1
      with:
        body_path: panvk_workdir/description
        name: ${{ steps.versions.outputs.name }}
        tag_name: ${{ steps.versions.outputs.tag }}
        files: |
           panvk_workdir/${{ steps.versions.outputs.filename }}.zip

    - name: Release "panvk" with experimental
      if: ${{ contains(steps.versions.outputs.experimental, 'true') }}
      uses: softprops/action-gh-release@v1
      with:
        body_path: panvk_workdir/description
        name: ${{ steps.versions.outputs.name }}
        tag_name: ${{ steps.versions.outputs.tag }}
        files: |
           panvk_workdir/${{ steps.versions.outputs.filename }}_experimental.zip
      
    - name: Release "panvk" with patched
      if: ${{ contains(steps.versions.outputs.patched, 'true') }}
      uses: softprops/action-gh-release@v1
      with:
        body_path: panvk_workdir/description
        name: ${{ steps.versions.outputs.name }}
        tag_name: ${{ steps.versions.outputs.tag }}
        files: |
           panvk_workdir/${{ steps.versions.outputs.filename }}_patched.zip
